import { CommonModule } from '@angular/common';
import { Component, Input, OnDestroy, OnInit, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { DiaryDataService } from '../core/diary-data.service';
import { UiStateService } from '../core/ui-state.service';
import { AuthService } from '../core/auth.service';
import { PdfExportService } from '../core/pdf-export.service';
import { SupabaseClientService } from '../core/supabase-client.service';
import { StorageService } from '../core/storage.service';
import { GlobalWorkerOptions, getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';
import { AppDropdownComponent } from '../shared/app-dropdown.component';
import { AppDatepickerComponent } from '../shared/app-datepicker.component';
import { AppTimepickerComponent } from '../shared/app-timepicker.component';
import { DiaryRow, FieldDefinition, SectionDefinition, SectionId, sectionById } from '../models/diary.models';

@Component({
  selector: 'tc-feature-page', standalone: true, imports: [CommonModule, FormsModule, RouterLink, AppDropdownComponent, AppDatepickerComponent, AppTimepickerComponent], template: `
  @if (section) {
    <section class="space-y-5">
      <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">IL TUO DIARIO · {{ section.label | uppercase }}</p><h1 class="page-title">{{ section.title }}</h1><p class="mt-2 max-w-2xl text-sm text-slate-500 dark:text-slate-400">{{ section.description }}</p></div>
        <div class="flex gap-2"><button type="button" class="button-secondary" (click)="refresh()">Aggiorna</button>@if (section.id !== 'reports') {<button type="button" class="button-primary" [disabled]="section.id !== 'children' && !children.length" (click)="openForm()"><span aria-hidden="true">＋</span> Aggiungi</button>}</div>
      </header>
      @if (section.id === 'expenses') {<div class="grid grid-cols-2 gap-3 lg:grid-cols-3"><div class="stat-card"><span>Totale registrato</span><strong>{{ total | currency:'EUR':'symbol':'1.2-2':'it' }}</strong></div><div class="stat-card"><span>Chilometri</span><strong>{{ kilometers }} km</strong></div><div class="stat-card col-span-2 lg:col-span-1"><span>Quota chilometrica stimata</span><strong>{{ kmRefund | currency:'EUR':'symbol':'1.2-2':'it' }}</strong></div></div>}
      @if (section.id === 'reports') {<div class="panel flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold">Report per il team clinico</h2><p class="mt-1 text-sm text-slate-500">Esporta le voci della sezione corrente in un PDF pronto per la visita.</p></div><button type="button" class="button-primary" (click)="exportReport()">Scarica PDF</button></div>}
      @if (section.id === 'reports') {<div class="panel grid gap-3 sm:grid-cols-3"><label class="form-field"><span>Dal</span><app-datepicker label="Data iniziale" [value]="reportFrom()" (dateChange)="reportFrom.set($event)" /></label><label class="form-field"><span>Al</span><app-datepicker label="Data finale" [value]="reportTo()" (dateChange)="reportTo.set($event)" /></label><label class="form-field"><span>Categoria</span><app-dropdown [options]="reportCategories" [value]="reportCategory()" placeholder="Tutte le categorie" (selection)="reportCategory.set($event)" /></label></div>}
      @if (section.id !== 'children' && children.length) {<div class="flex items-center gap-3 rounded-2xl bg-white px-4 py-3 shadow-sm dark:bg-slate-900"><span class="text-xs font-semibold uppercase tracking-wide text-slate-400">Bambino</span><app-dropdown class="w-full max-w-xs" [options]="childNames" [value]="selectedChildName()" placeholder="Scegli profilo" (selection)="selectChild($event)" /></div>}
      @if (section.id !== 'children' && !children.length) {<div class="notice-error !border-amber-200 !bg-amber-50 !text-amber-900 dark:!border-amber-800 dark:!bg-amber-950/40 dark:!text-amber-100">Crea prima un profilo bambino per collegare in modo sicuro le registrazioni. <a routerLink="/children" class="font-bold underline">Vai ai profili</a></div>}
      @if (data.error()) {<div class="notice-error" role="alert">{{ data.error() }}</div>}
      @if (data.syncing()) {<div class="panel py-12 text-center text-sm text-slate-500">Aggiornamento del diario…</div>}
      @else if (!data.rows().length && section.id !== 'reports') {<div class="panel flex flex-col items-center px-6 py-14 text-center"><div class="mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-teal-50 text-2xl text-teal-700 dark:bg-teal-900/30 dark:text-teal-200">{{ section.id === 'children' ? '♡' : '＋' }}</div><h2 class="text-lg font-semibold">Ancora nessuna voce</h2><p class="mt-2 max-w-sm text-sm text-slate-500">{{ section.id === 'children' ? 'Crea un profilo per iniziare a organizzare il diario.' : 'Aggiungi la prima voce: potrai aggiornarla e condividerla durante la visita.' }}</p><button class="button-primary mt-5" (click)="openForm()">{{ section.id === 'children' ? 'Aggiungi un bambino' : 'Aggiungi una voce' }}</button></div>}
      @else {<div class="grid gap-3 md:grid-cols-2">@for (row of filteredRows; track row['id']) {<article class="panel group"><div class="flex items-start justify-between gap-4"><div class="min-w-0"><p class="text-xs font-semibold uppercase tracking-wide text-teal-700 dark:text-teal-300">{{ section.id === 'contacts' ? value(row,'category') : ((value(row, 'date') || value(row, 'start_date') || value(row, 'created_at')) | date:'d MMM y') }}</p><h2 class="mt-1 truncate text-base font-semibold">{{ value(row, 'title') || value(row, 'name') || value(row, 'category') || 'Voce del diario' }}</h2>@if(section.id==='contacts' && value(row,'role')){<p class="mt-1 text-sm text-slate-500">{{ value(row,'role') }}</p>}</div><div class="flex gap-3"><button type="button" class="text-sm text-teal-700 hover:underline dark:text-teal-300" (click)="edit(row)">Modifica</button><button type="button" class="text-sm text-slate-400 hover:text-rose-600" [attr.aria-label]="'Elimina '+(value(row,'title') || value(row,'name') || 'voce')" (click)="remove(row)">Elimina</button></div></div><div class="mt-3 flex flex-wrap gap-2">@for (field of visibleFields(row); track field.key) {@if (value(row, field.key)) {<span class="tag"><b>{{ field.label }}:</b> @if(section.id==='contacts' && field.key==='phone'){<a class="underline" [href]="'tel:'+value(row,field.key)">{{ value(row,field.key) }}</a>}@else if(section.id==='contacts' && field.key==='email'){<a class="underline" [href]="'mailto:'+value(row,field.key)">{{ value(row,field.key) }}</a>}@else { {{ value(row, field.key) }} }</span>}}</div>@if((section.id==='documents' && value(row,'storage_path')) || (section.id==='expenses' && value(row,'receipt_path'))){<button type="button" class="mt-3 text-sm font-semibold text-teal-700 hover:underline dark:text-teal-300" (click)="openDocument(row)">Apri allegato →</button>}</article>}</div>}
    </section>
    @if (isFormOpen()) {<div class="modal-backdrop" (click)="closeForm()"><section role="dialog" aria-modal="true" aria-labelledby="dialog-title" class="modal-panel" (click)="$event.stopPropagation()"><header class="flex items-start justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><div><p class="eyebrow">NUOVA REGISTRAZIONE</p><h2 id="dialog-title" class="text-xl font-semibold">{{ section.id === 'children' ? 'Profilo bambino' : 'Aggiungi una voce' }}</h2></div><button type="button" class="icon-button" aria-label="Chiudi" (click)="closeForm()">×</button></header>
        <form class="space-y-4 overflow-y-auto px-5 py-5" (ngSubmit)="save()"><div class="grid gap-4 sm:grid-cols-2">@for (field of section.fields; track field.key) {<label class="form-field" [class.full-span]="field.kind === 'textarea' || field.kind === 'file'"><span>{{ field.label }}@if(field.required){<i class="text-rose-500"> *</i>}</span>
          @switch(field.kind) {
            @case('select') {<app-dropdown [options]="field.options ?? []" [value]="form[field.key]" [placeholder]="field.placeholder ?? 'Seleziona'" (selection)="setField(field,$event)" />}
            @case('date') {<app-datepicker [label]="field.label" [value]="form[field.key]" (dateChange)="setField(field,$event)" />}
            @case('time') {<app-timepicker [label]="field.label" [value]="form[field.key]" (timeChange)="setField(field,$event)" />}
            @case('textarea') {<textarea class="field-control min-h-24 resize-y" [name]="field.key" [(ngModel)]="form[field.key]" [required]="field.required ?? false" rows="3"></textarea>}
            @case('file') {<input class="field-control file:mr-3 file:rounded-lg file:border-0 file:bg-teal-50 file:px-3 file:py-2 file:font-medium file:text-teal-800" type="file" [required]="field.required ?? false" accept=".pdf,image/jpeg,image/png,image/webp,image/heic" (change)="setFile(field,$event)"><small class="text-xs text-slate-400">I file vengono caricati nel bucket privato quando Supabase è configurato. Dai PDF con testo selezionabile viene estratto anche il testo per la ricerca.</small>}
            @default {<input class="field-control" [type]="field.kind === 'number' ? 'number' : 'text'" [name]="field.key" [(ngModel)]="form[field.key]" [required]="field.required ?? false" [placeholder]="field.placeholder ?? ''" [step]="field.kind === 'number' ? 'any' : null">}
          }
        </label>}</div>
          @if(section.id === 'children' && !form['user_id']) {<p class="text-xs text-slate-500">I dati restano privati e sono associati al tuo account.</p>}
          <footer class="flex justify-end gap-2 border-t border-slate-100 pt-4 dark:border-slate-800"><button type="button" class="button-secondary" (click)="closeForm()">Annulla</button><button class="button-primary" type="submit" [disabled]="saving()">{{ extracting() ? 'Estrazione testo…' : saving() ? 'Salvataggio…' : 'Salva nel diario' }}</button></footer>
        </form></section></div>}
  }
  ` })
export class FeaturePageComponent implements OnInit, OnDestroy {
  @Input({ required: true }) sectionId!: SectionId;
  readonly data = inject(DiaryDataService); readonly ui = inject(UiStateService); private readonly auth = inject(AuthService); private readonly pdf = inject(PdfExportService); private readonly supabase = inject(SupabaseClientService); private readonly storage = inject(StorageService);
  readonly isFormOpen = signal(false); readonly saving = signal(false); readonly extracting = signal(false); readonly initialized = signal(false); readonly selectedChildId = signal(''); readonly selectedChildName = signal(''); readonly reportFrom = signal(''); readonly reportTo = signal(''); readonly reportCategory = signal(''); readonly reportCategories = ['Farmaci', 'Eventi e sintomi', 'Terapie', 'Documenti', 'Spese e rimborsi']; readonly children: DiaryRow[] = []; form: Record<string, string> = {}; private attachedFile: File | null = null; private editingId = '';
  private readonly accountChangeEffect = effect(() => { const ready = this.initialized(); this.auth.user(); if (ready) queueMicrotask(() => void this.reloadForAccount()); });
  get section(): SectionDefinition { return sectionById(this.sectionId)!; }
  get childNames(): string[] { return this.children.map(c => String(c['name'])); }
  get total(): number { return this.data.rows().reduce((sum, row) => sum + (Number(row['amount']) || (Number(row['distance_km']) || 0) * (Number(row['rate_per_km']) || 0)), 0); }
  get kilometers(): number { return this.data.rows().reduce((sum, row) => sum + (Number(row['distance_km']) || 0), 0); }
  get kmRefund(): number { return this.data.rows().reduce((sum, row) => sum + (Number(row['distance_km']) || 0) * (Number(row['rate_per_km']) || 0), 0); }
  get filteredRows(): DiaryRow[] { return this.data.rows().filter(row => { const date = String(row['date'] ?? row['start_date'] ?? row['created_at'] ?? '').slice(0, 10); const category = String(row['record_type'] ?? ''); const categoryLabel = ({ medications: 'Farmaci', health_events: 'Eventi e sintomi', therapies: 'Terapie', documents: 'Documenti', expenses: 'Spese e rimborsi' } as Record<string, string>)[category] ?? ''; return (!this.reportFrom() || date >= this.reportFrom()) && (!this.reportTo() || date <= this.reportTo()) && (!this.reportCategory() || categoryLabel === this.reportCategory()); }); }
  async ngOnInit(): Promise<void> { await this.auth.ready; await this.loadChildren(); await this.refresh(); this.initialized.set(true); }
  ngOnDestroy(): void { if (this.isFormOpen()) this.closeForm(); else this.ui.resetBodyScroll(); }
  async refresh(): Promise<void> { if (this.sectionId === 'reports') { await this.data.loadReport(this.selectedChildId() || undefined); return; } if (this.sectionId !== 'children' && this.selectedChildId()) { const client = this.supabase.client; if (client && this.auth.user()) { this.data.syncing.set(true); const { data, error } = await client.from(this.sectionId).select('*').eq('child_id', this.selectedChildId()).order('created_at', { ascending: false }); if (!error) this.data.rows.set(data as DiaryRow[]); else this.data.error.set(error.message); this.data.syncing.set(false); return; } await this.data.load(this.sectionId); this.data.rows.set(this.data.rows().filter(row => row['child_id'] === this.selectedChildId())); return; } await this.data.load(this.sectionId); }
  value(row: DiaryRow, key: string): string { const value = row[key]; return value == null ? '' : String(value); }
  visibleFields(row: DiaryRow): FieldDefinition[] { if (this.sectionId === 'reports') return ([{ key: 'record_type', label: 'Categoria', kind: 'text' }, { key: 'notes', label: 'Note', kind: 'text' }] as FieldDefinition[]).filter(field => row[field.key] != null); return this.section.fields.filter(field => !['file', 'name'].includes(field.key) && field.key !== 'title' && row[field.key] != null); }
  setField(field: FieldDefinition, value: string): void { this.form[field.key] = value; }
  setFile(field: FieldDefinition, event: Event): void { const file = (event.target as HTMLInputElement).files?.[0]; if (file) { this.attachedFile = file; this.form[field.key] = file.name; } }
  selectChild(name: string): void { const child = this.children.find(item => item['name'] === name); this.selectedChildName.set(name); this.selectedChildId.set(child?.id ?? ''); void this.refresh(); }
  openForm(): void { this.form = {}; this.attachedFile = null; this.editingId = ''; this.isFormOpen.set(true); this.ui.setModal(true); }
  edit(row: DiaryRow): void { this.form = {}; for (const field of this.section.fields) { const value = row[field.key]; if (value != null && typeof value !== 'object') this.form[field.key] = String(value); } this.editingId = row.id; this.isFormOpen.set(true); this.ui.setModal(true); }
  closeForm(): void { this.isFormOpen.set(false); this.ui.setModal(false); }
  async save(): Promise<void> { this.saving.set(true); const value: Record<string, unknown> = { ...this.form }; for (const key of ['amount', 'distance_km', 'rate_per_km']) if (value[key]) value[key] = Number(value[key]); if (this.sectionId === 'children' && this.auth.user()) value['user_id'] = this.auth.user()!.id; if (this.sectionId === 'documents' && this.attachedFile && (this.attachedFile.type === 'application/pdf' || this.attachedFile.name.toLowerCase().endsWith('.pdf'))) { this.extracting.set(true); try { value['extracted_text'] = await this.extractPdfText(this.attachedFile); if (!value['extracted_text']) this.data.error.set('Il PDF non contiene testo selezionabile. I PDF composti solo da scansioni non sono indicizzati.'); } catch { value['extracted_text'] = ''; this.data.error.set('Non è stato possibile estrarre il testo dal PDF; il documento verrà comunque salvato.'); } finally { this.extracting.set(false); } } if (this.attachedFile && this.selectedChildId() && ['documents', 'expenses'].includes(this.sectionId)) { const path = await this.storage.upload(this.attachedFile, this.selectedChildId()); if (path) value[this.sectionId === 'documents' ? 'storage_path' : 'receipt_path'] = path; else if (this.supabase.configured && this.auth.user()) { this.data.error.set('Caricamento non riuscito. Verifica il bucket e riprova.'); this.saving.set(false); return; } } if (this.sectionId === 'documents' && value['storage_path']) delete value['file']; if (this.sectionId === 'expenses' && value['receipt_path']) delete value['receipt']; const ok = this.editingId ? await this.data.update(this.sectionId, this.editingId, value) : await this.data.save(this.sectionId, value, this.sectionId === 'children' ? undefined : this.selectedChildId() || undefined); this.saving.set(false); if (ok) this.closeForm(); }
  private async extractPdfText(file: File): Promise<string> { GlobalWorkerOptions.workerSrc = new URL('assets/pdfjs/pdf.worker.min.mjs', document.baseURI).toString(); const pdf = await getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise; const pages: string[] = []; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber++) { const page = await pdf.getPage(pageNumber); const content = await page.getTextContent(); pages.push(content.items.map(item => 'str' in item ? item.str : '').filter(Boolean).join(' ')); } await pdf.destroy(); return pages.join('\n').replace(/[ \t]+/g, ' ').trim(); }
  async remove(row: DiaryRow): Promise<void> { if (confirm('Vuoi eliminare questa voce dal diario?')) await this.data.remove(this.sectionId, row); }
  exportReport(): void { this.pdf.export(this.section, this.filteredRows, this.selectedChildName()); }
  async openDocument(row: DiaryRow): Promise<void> { const path = row['storage_path'] ?? row['receipt_path']; const url = await this.storage.signedUrl(String(path)); if (url) window.open(url, '_blank', 'noopener'); else this.data.error.set('Impossibile aprire il file. Accedi al tuo account e riprova.'); }
  private async loadChildren(): Promise<void> { this.children.splice(0); if (this.sectionId === 'children') return; const client = this.supabase.client; if (client && this.auth.user()) { const { data } = await client.from('children').select('id,name').order('name'); this.children.push(...(data ?? []) as DiaryRow[]); } else { const stored = JSON.parse(localStorage.getItem('trialcare-diary-v1') ?? '{}') as Record<string, DiaryRow[]>; this.children.push(...(stored['children'] ?? [])); } if (this.children.length) { this.selectedChildId.set(this.children[0].id); this.selectedChildName.set(String(this.children[0]['name'])); } else { this.selectedChildId.set(''); this.selectedChildName.set(''); } }
  private async reloadForAccount(): Promise<void> { await this.loadChildren(); await this.refresh(); }
}
