import { Component, OnDestroy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from './core/auth.service';
import { SupabaseClientService } from './core/supabase-client.service';
import { UiStateService } from './core/ui-state.service';
import { LoginComponent } from './auth/login.component';
import { SECTIONS } from './models/diary.models';

@Component({selector:'tc-root',standalone:true,imports:[CommonModule,RouterOutlet,RouterLink,RouterLinkActive,LoginComponent],template:`
  <div class="app-frame min-h-dvh bg-[#f6f8f5] text-slate-800 dark:bg-[#0e1719] dark:text-slate-100"><aside class="sidebar hidden lg:flex"><a routerLink="/dashboard" class="brand-lockup"><span class="brand-mark">♡</span><span><strong>trialcare</strong><small>DIARY</small></span></a><p class="eyebrow mt-10 px-3">IL TUO SPAZIO</p><nav class="mt-3 space-y-1"><a routerLink="/dashboard" routerLinkActive="nav-active" class="nav-link"><span class="nav-glyph">⌂</span>Panoramica</a>@for(section of navigation;track section.id){<a [routerLink]="'/' + section.id" routerLinkActive="nav-active" class="nav-link"><span class="nav-glyph">{{glyph(section.id)}}</span>{{section.label}}</a>}</nav><div class="sidebar-footer"><div class="avatar">{{auth.user()?.email?.slice(0,1)?.toUpperCase() || 'G'}}</div><div class="min-w-0 flex-1"><strong class="block truncate text-sm">{{auth.user()?.email || 'Diario personale'}}</strong><span class="text-xs text-slate-400">{{auth.user()?'Sincronizzato':'Modalità privata'}}</span></div>@if(auth.user()){<button class="icon-button" aria-label="Esci" title="Esci" (click)="auth.signOut()">↗</button>}</div></aside>
  <div class="main-column"><header class="topbar"><a routerLink="/dashboard" class="brand-lockup lg:hidden"><span class="brand-mark">♡</span><span><strong>trialcare</strong><small>DIARY</small></span></a><div class="hidden text-sm text-slate-500 lg:block">Un posto gentile per tenere il filo.</div><div class="ml-auto flex items-center gap-2"><span class="connection-pill" [class.connection-live]="supabase.configured && auth.user()"><i></i>{{auth.user()?'Dati sincronizzati':'Solo su questo dispositivo'}}</span><button type="button" class="icon-button" [attr.aria-label]="ui.darkMode()?'Attiva tema chiaro':'Attiva tema scuro'" (click)="ui.toggleTheme()">{{ui.darkMode()?'☼':'◐'}}</button>@if(!auth.user()){<button type="button" class="button-secondary hidden sm:inline-flex" (click)="showLogin()">Accedi</button>}@else{<button type="button" class="icon-button lg:hidden" aria-label="Esci" (click)="auth.signOut()">↗</button>}</div></header><main class="page-content"><div class="mx-auto max-w-6xl"><router-outlet /></div></main>
  @if(!supabase.configured && setupNoteVisible()){<div class="setup-note"><span class="text-teal-700 dark:text-teal-300">●</span><span>Modalità dimostrativa: le voci restano nel browser e non sono cifrate. Configura Supabase prima di inserire dati clinici reali.</span><button type="button" aria-label="Chiudi" (click)="setupNoteVisible.set(false)">×</button></div>}</div>
  <nav class="bottom-nav lg:hidden"><a routerLink="/dashboard" routerLinkActive="bottom-active" [routerLinkActiveOptions]="{exact:true}"><span>⌂</span>Home</a>@for(section of bottomSections;track section.id){<a [routerLink]="'/' + section.id" routerLinkActive="bottom-active"><span>{{glyph(section.id)}}</span>{{section.shortLabel}}</a>}<button type="button" (click)="auth.user()?auth.signOut():showLogin()"><span>☻</span>{{auth.user()?'Account':'Accedi'}}</button></nav>@if(loginOpen()){<tc-login (dismiss)="hideLogin()" />}</div>`})
export class AppComponent implements OnDestroy {
 readonly auth=inject(AuthService); readonly supabase=inject(SupabaseClientService); readonly ui=inject(UiStateService); readonly loginOpen=signal(false); readonly setupNoteVisible=signal(true); readonly navigation=SECTIONS; readonly bottomSections=SECTIONS.filter(s=>['children','medications','health_events','expenses'].includes(s.id));
 showLogin():void{this.loginOpen.set(true);this.ui.setModal(true);} hideLogin():void{this.loginOpen.set(false);this.ui.setModal(false);}
 glyph(id:string):string{return ({children:'♡',medications:'＋',health_events:'⌁',therapies:'✳',documents:'▤',expenses:'€',reports:'▥'} as Record<string,string>)[id]??'·';}
 ngOnDestroy():void{if(this.loginOpen())this.hideLogin();else this.ui.resetBodyScroll();}
}
