import { Component, OnDestroy, effect, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from './core/auth.service';
import { BiometricAuthService } from './core/biometric-auth.service';
import { SupabaseClientService } from './core/supabase-client.service';
import { UiStateService } from './core/ui-state.service';
import { LoginComponent } from './auth/login.component';
import { SECTIONS } from './models/diary.models';

@Component({selector:'tc-root',standalone:true,imports:[CommonModule,RouterOutlet,RouterLink,RouterLinkActive,LoginComponent],template:`
  @if(!auth.user()){<tc-login />}@else if(biometricLocked()){<div class="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="biometric-title" class="modal-panel max-w-md p-6 text-center"><p class="eyebrow">ACCESSO PERSONALE</p><h2 id="biometric-title" class="mt-1 text-2xl font-semibold">Sblocca TrialCare</h2><p class="mt-2 text-sm text-slate-500">Conferma la tua identità con il dispositivo per aprire il diario.</p>@if(biometrics.error()){<p role="alert" class="notice-error mt-4">{{biometrics.error()}}</p>}<button type="button" class="button-primary mt-5 w-full justify-center" [disabled]="biometrics.busy()" (click)="unlockWithBiometrics()">{{biometrics.busy()?'Verifica in corso…':'Sblocca con biometria'}}</button><button type="button" class="mt-3 w-full py-2 text-sm text-slate-500 hover:underline" (click)="signOut()">Usa email e password</button></section></div>}@else{
  <div class="app-frame min-h-dvh bg-[#f6f8f5] text-slate-800 dark:bg-[#0e1719] dark:text-slate-100"><aside class="sidebar hidden lg:flex"><a routerLink="/dashboard" class="brand-lockup"><span class="brand-mark">♡</span><span><strong>trialcare</strong><small>DIARY</small></span></a><p class="eyebrow mt-10 px-3">IL TUO SPAZIO</p><nav class="mt-3 space-y-1"><a routerLink="/dashboard" routerLinkActive="nav-active" class="nav-link"><span class="nav-glyph">⌂</span>Panoramica</a>@for(section of navigation;track section.id){<a [routerLink]="'/' + section.id" routerLinkActive="nav-active" class="nav-link"><span class="nav-glyph">{{glyph(section.id)}}</span>{{section.label}}</a>}</nav><div class="sidebar-footer"><div class="avatar">{{auth.user()?.email?.slice(0,1)?.toUpperCase() || 'G'}}</div><div class="min-w-0 flex-1"><strong class="block truncate text-sm">{{auth.user()?.email || 'Diario personale'}}</strong><span class="text-xs text-slate-400">{{auth.user()?'Sincronizzato':'Modalità privata'}}</span></div>@if(auth.user() && biometrics.available() && !biometrics.enrolled()){<button type="button" class="icon-button" aria-label="Attiva accesso biometrico" (click)="biometrics.enroll()">⌘</button>}@if(auth.user() && biometrics.enrolled()){<button type="button" class="icon-button" aria-label="Disattiva accesso biometrico" (click)="biometrics.revoke()">⌘</button>}@if(auth.user()){<button class="icon-button" aria-label="Esci" title="Esci" (click)="signOut()">↗</button>}</div></aside>
  <div class="main-column"><header class="topbar"><a routerLink="/dashboard" class="brand-lockup lg:hidden"><span class="brand-mark">♡</span><span><strong>trialcare</strong><small>DIARY</small></span></a><div class="hidden text-sm text-slate-500 lg:block">Un posto gentile per tenere il filo.</div><div class="ml-auto flex items-center gap-2"><span class="connection-pill" [class.connection-live]="supabase.configured && auth.user()"><i></i>{{auth.user()?'Dati sincronizzati':'Solo su questo dispositivo'}}</span>@if(auth.user() && biometrics.available() && !biometrics.enrolled()){<button type="button" class="icon-button" aria-label="Attiva accesso biometrico" (click)="biometrics.enroll()">⌘</button>}@if(auth.user() && biometrics.enrolled()){<button type="button" class="icon-button" aria-label="Disattiva accesso biometrico" (click)="biometrics.revoke()">⌘</button>}<button type="button" class="icon-button" [attr.aria-label]="ui.darkMode()?'Attiva tema chiaro':'Attiva tema scuro'" (click)="ui.toggleTheme()">{{ui.darkMode()?'☼':'◐'}}</button><button type="button" class="icon-button lg:hidden" aria-label="Esci" (click)="signOut()">↗</button></div></header>@if(biometrics.error()){<p role="alert" class="notice-error mx-4 mt-3">{{biometrics.error()}}</p>}@if(biometrics.busy()){<p role="status" class="px-4 pt-2 text-sm text-slate-500">Verifica biometrica in corso…</p>}<main class="page-content"><div class="mx-auto max-w-6xl"><router-outlet /></div></main>
  @if(!supabase.configured && setupNoteVisible()){<div class="setup-note"><span class="text-teal-700 dark:text-teal-300">●</span><span>Modalità dimostrativa: le voci restano nel browser e non sono cifrate. Configura Supabase prima di inserire dati clinici reali.</span><button type="button" aria-label="Chiudi" (click)="setupNoteVisible.set(false)">×</button></div>}</div>
  <nav class="bottom-nav lg:hidden"><a routerLink="/dashboard" routerLinkActive="bottom-active" [routerLinkActiveOptions]="{exact:true}"><span>⌂</span>Home</a>@for(section of bottomSections;track section.id){<a [routerLink]="'/' + section.id" routerLinkActive="bottom-active" class="nav-link"><span>{{glyph(section.id)}}</span>{{section.shortLabel}}</a>}<button type="button" (click)="signOut()"><span>☻</span>Esci</button></nav></div>}
  @if(!authReady()){<div class="fixed inset-0 z-[100] grid place-items-center bg-[#f6f8f5] dark:bg-[#0e1719]" role="status">Verifica accesso…</div>}`})
export class AppComponent implements OnDestroy {
 readonly auth=inject(AuthService); readonly biometrics=inject(BiometricAuthService); readonly supabase=inject(SupabaseClientService); readonly ui=inject(UiStateService); readonly router=inject(Router); readonly setupNoteVisible=signal(true); readonly navigation=SECTIONS; readonly bottomSections=SECTIONS.filter(s=>['children','medications','health_events','contacts'].includes(s.id));
 readonly authReady=signal(false);
 readonly biometricLocked=signal(false);
 constructor(){void this.auth.ready.finally(()=>this.authReady.set(true)); effect(()=>{const user=this.auth.user();const ready=this.authReady();const enrolled=this.biometrics.enrolled();if(user&&ready){if(enrolled&&sessionStorage.getItem('trialcare-biometric-unlocked')!=='true')this.biometricLocked.set(true);const path=window.location.hash.slice(1);if(path&&path!=='/'&&!path.startsWith('/login'))void this.router.navigateByUrl(path);}});}
 async unlockWithBiometrics():Promise<void>{await this.biometrics.signIn();if(!this.biometrics.error()){sessionStorage.setItem('trialcare-biometric-unlocked','true');this.biometricLocked.set(false);}}
 async signOut():Promise<void>{this.biometrics.revoke();sessionStorage.removeItem('trialcare-biometric-unlocked');await this.auth.signOut();}
 glyph(id:string):string{return ({children:'♡',medications:'＋',health_events:'⌁',therapies:'✳',documents:'▤',expenses:'€',contacts:'☎',reports:'▥'} as Record<string,string>)[id]??'·';}
 ngOnDestroy():void{this.ui.resetBodyScroll();}
}
