import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { SECTIONS } from '../models/diary.models';

@Component({selector:'tc-dashboard',standalone:true,imports:[RouterLink],template:`
  <section class="space-y-6"><div class="welcome-card"><div class="relative z-10 max-w-2xl"><p class="text-sm font-semibold text-teal-100">IL TUO SPAZIO DI CURA</p><h1 class="mt-3 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">Un diario chiaro,<br class="sm:hidden"> al vostro fianco.</h1><p class="mt-3 max-w-lg text-sm leading-6 text-teal-50/85">Raccogli informazioni e piccoli dettagli quotidiani. Potrai ritrovarli e condividerli con il team clinico quando serve.</p><a routerLink="/children" class="mt-5 inline-flex rounded-xl bg-white px-4 py-3 text-sm font-semibold !text-teal-900 shadow-sm transition hover:bg-teal-50">Crea un profilo <span class="ml-2">→</span></a></div><div aria-hidden="true" class="welcome-orbit">♡</div></div>
  <div class="flex items-end justify-between gap-4"><div><p class="eyebrow">ACCESSO RAPIDO</p><h2 class="mt-1 text-xl font-semibold">Il diario di oggi</h2></div><a routerLink="/reports" class="text-sm font-semibold text-teal-700 hover:underline dark:text-teal-300">Prepara report →</a></div>
  <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@for(item of quickLinks;track item.id){<a class="quick-card group" [routerLink]="'/' + item.id"><div class="flex items-start justify-between"><span class="quick-icon">{{item.glyph}}</span><span class="text-slate-300 transition group-hover:translate-x-1 group-hover:text-teal-600">↗</span></div><h3 class="mt-4 font-semibold">{{item.title}}</h3><p class="mt-1 text-sm leading-5 text-slate-500 dark:text-slate-400">{{item.description}}</p></a>}</div>
  <div class="panel flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-start gap-3"><span class="mt-0.5 text-xl text-amber-500">✦</span><div><h2 class="font-semibold">Piccoli appunti, grande aiuto</h2><p class="mt-1 text-sm leading-5 text-slate-500 dark:text-slate-400">Anche un sintomo lieve o una ricevuta possono essere utili alla prossima visita.</p></div></div><a routerLink="/health_events" class="button-secondary shrink-0">Registra un evento</a></div></section>`})
export class DashboardComponent { readonly quickLinks=SECTIONS.filter(item=>item.id!=='children').slice(0,5).map((item,index)=>({...item,glyph:['◉','⌁','♡','▤','€'][index]})); }
